### ISSUE TITLE
Why are you writing your own encryption function?

### ISSUE THREAD

**Issue by shouston3** [FAC8-TheGoodParts/twtt-postgres#11]
It's cool that you are trying to make a encryption function and take an interest in cryptography, but perhaps this should have been more of a stretch goal for after the project was finished and other stretch goals were addressed (e.g. sockets).

Also think instead of doing this, you could have spent your time looking into node modules which use well validated algorithms (such as bcrypt) and compare the benefits of the different modules out there and learn how to implement them

Node does have a native crypto module here: https://nodejs.org/api/crypto.html
Check out this for an example of using the module
https://github.com/chris-rock/node-crypto-examples/blob/master/crypto-gcm.js

**Comment by matthewiiv** [comment]
The encryption function was just a side project while we worked on the backend tests. I'll take a look at those node modules.
