### ISSUE TITLE
new tweet button is not sending the correct url

### ISSUE THREAD

**Issue by daymos** [FAC8-TheGoodParts/twtt-postgres#24]

**Comment by gabrielperales** [comment]
that functionality is not implemented yet. I can't run the server to test that.

I got this error:
```
Server listening on: http://localhost:8080
/Users/gabriel/workspace/twtt-postgres/src/helpers.js:36
    if (err) throw err;
             ^

error: database "gabriel" does not exist
```

**Comment by gabrielperales** [comment]
I have implemented that functionality but I couldn't try it.

**Comment by daymos** [comment]
im on it

**Comment by daymos** [comment]
I cannot replicate the error. You are not connecting to the remote db. Are you sure you have this line const dbUrl = 'postgres://dexgnclp:zyHHNCMlgIwDg0BO5zyg7D82v89w_hVm@horton.elephantsql.com:5432/dexgnclp';
in file controller?

**Comment by daymos** [comment]
I also noted that the create twtt function doesn not build the url according to the readme. It should include /twtt

**Comment by gabrielperales** [comment]
it is here https://github.com/FAC8-TheGoodParts/twtt-postgres/blob/master/public/js/api.js#L56, and it is ok

**Comment by gabrielperales** [comment]
the url is ok, the thing is that the backend response is 204 instead of 201 and that raise an error in the browser `VM1064:1 Uncaught SyntaxError: Unexpected end of JSON input`

**Comment by daymos** [comment]
ok corrected the response. 
But when I click send, the server receive this url: '/?message=the tweet content' so the handler doesnt do anything

**Comment by gabrielperales** [comment]
???? the message is in the payload (it is a post request) ... so the  message is not a url parameter

**Comment by daymos** [comment]
it was there man, don't understand it. Your last commit fix it.
